- name: Install InfluxDB
  yum: name=https://s3.amazonaws.com/influxdb/influxdb-{{ influxdb.version }}.{{ ansible_architecture }}.rpm state=present

- name: Configure InfluxDB
  template: src=config.toml.j2 dest=/opt/influxdb/shared/config.toml

- name: Restart InfluxDB service
  service: name=influxdb state=restarted

- name: Wait for InfluxDB API to become available
  wait_for: port=8086 state=present

- name: Setting root password
  uri: 'url=http://localhost:8086/cluster_admins/root?u=root&p=root method=POST body={\"password\":\"{{ influxdb.root_password }}\"} status_code=200'
  ignore_errors: yes

- name: Create databases
  uri: url=http://localhost:8086/cluster/database_configs/{{ item.name }}?u=root&p={{ influxdb.root_password }} method=POST body='{{ lookup("template", "../templates/db.json.j2") }}' status_code=201
  with_items: influxdb.databases
  ignore_errors: yes
