- name: Install PHP-FPM
  yum: name=php-fpm state=latest
  when: ansible_os_family == "RedHat"

- name: Install additional PHP libraries
  yum: name={{ item }} state=latest
  with_items:
    - php-gd
  when: ansible_os_family == "RedHat"

- name: Install PECL extensions
  yum: name={{ item }} state=latest
  with_items:
    - php-pecl-zendopcache
    - php-pecl-apcu
  when: ansible_os_family == "RedHat"

- name: Restart and enable PHP-FPM
  service: name=php-fpm state=restarted enabled=yes
