- name: MySQL server installation
  yum: name=mariadb-server state=latest
  when: ansible_os_family == "RedHat"

- name: MySQL running and enabled
  service: name=mariadb state=started enabled=yes
  when: ansible_os_family == "RedHat"

- name: Install Python MySQL driver
  yum: name=MySQL-python state=latest
  when: ansible_os_family == "RedHat"
