collectd:
  hostname: example
  plugins:
    - cpu
    - df
    - disk
    - entropy
    - interface
    - load
    - memory
    - processes
    - swap
    - uptime
    - users
  network:
    enable: yes
    report: yes

    listen: yes
    listen_host: 0.0.0.0
    listen_port: 25826
    listen_encrypt: yes
    listen_username: collectd
    listen_password: password

    servers:
      - host: 127.0.0.1
        port: 25827
        encrypt: no
