- name: Enabling EPEL repository
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat"

- name: Update apt repositories
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install Python httplib2
  yum: name=python-httplib2 state=latest
  when: ansible_os_family == "RedHat"

- name: Install Python httplib2
  apt: name=python-httplib2 state=latest
  when: ansible_os_family == "Debian"
